### ISSUE TITLE
General Bugs - `upload` is undefined

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#204]
## Current State
Once in a while we see the following error when loading the homepage in [datadog](https://app.datadoghq.com/logs?query=service%3Acpf-reporter%20&cols=host%2Cservice&event=AgAAAY7uFJnhJQkIAgAAAAAAAAAYAAAAAEFZN3VGSnRvQUFCZ1NCSlVPVlBoSlFBRwAAACQAAAAAMDE4ZWVlMTQtYjk4Ny00NmU4LWJmYTYtNTE3NmRlZmZjMWQ1&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=2835888812452062688&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1713390429091&to_ts=1713391329091&live=true):
```
TypeError: Cannot read properties of undefined (reading 'upload')
    at Object.upload (/var/task/api/dist/services/uploads/uploads.js:51:23)
    at Object.upload (/var/task/node_modules/@redwoodjs/graphql-server/dist/makeMergedSchema.js:73:32)
    at useRedwoodDirectiveValidatorResolver (/var/task/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodDirective.js:109:22)
    at /opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/graphql.js:239:25
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at callInAsyncScope (/opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/graphql.js:232:13)
    at resolveAsync (/opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/graphql.js:219:12)
    at executeField (/var/task/node_modules/@graphql-tools/executor/cjs/execution/execute.js:331:24)
    at executeFields (/var/task/node_modules/@graphql-tools/executor/cjs/execution/execute.js:271:28)
    at executeOperation (/var/task/node_modules/@graphql-tools/executor/cjs/execution/execute.js:219:18)
```

## Expected State
1. Identify the source of the problem
2. Resolve the problem so it does not happen in the future.

**Comment by as1729** [comment]
I believe this was resolved as part of the prisma initialization problem that was fixed in #268
